#
#
# CREATE A COPY OF THIS FILE AS test_config.ini WITH YOUR 
#  XERO PUBLIC APPLICATION API CREDENTIALS
#  
# 
#

[PRIVATE_APPLICATION]
# CONSUMER_KEY    = YOUR_OAUTH_CONSUMER_KEY, 
# CONSUMER_SECRET = YOUR_OAUTH_CONSUMER_SECRET, 
# KEYFILE         = /path/to/privatekey.pem

[PUBLIC_APPLICATION]
 NAME            = 
 CONSUMER_KEY    = 
 CONSUMER_SECRET = 


[PARTNER_APPLICATION]
# NOT IMPLEMENTED YET


[MOJO_APP_PARAMS]
WEBSOCKET_URL  = ws://localhost:3000/data